CREATE TABLE users (
   id SERIAL PRIMARY KEY,
   password VARCHAR(255) NOT NULL,
   username VARCHAR(50) NOT NULL,
   email VARCHAR(100) NOT NULL,
   role VARCHAR(50) NOT NULL,
   user_type VARCHAR(50) NOT NULL
);